### ISSUE TITLE
Can't get users of a Course from Moodle.

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#89]
/api1/users is not returning users from Moodle for certain users.

**Comment by uzuzjmd** [comment]
![userapi](https://cloud.githubusercontent.com/assets/1481930/18866515/9a19810e-84a0-11e6-8986-a95be51ff8ef.png)

The problem seems to be specific to the users you are using. The screenshot shows that the api works in principle. 

Since the moodle plugin is using the activity log files, possibly the users created need to have viewed the course previously or the passwords are special. 

There is an enrolement API in moodle: https://docs.moodle.org/dev/Enrolment_API#get_enrolled_users.28.29

Please check if the issue remains if user actively participate in the course. If the issue remains a rewrite of the moodle rest plugin is necessary using the api above.

**Comment by mantir** [comment]
Would it be possible to add a filter for a coursId, because the system is returning hundreds of users if a certain users is requesting it.

**Comment by uzuzjmd** [comment]
The users returned should only be users that share a course with the user providing the credentials. So it is likely you used an admin user which is not advisable.
