### ISSUE TITLE
Sync Function with moodle db

### ISSUE THREAD

**Issue by uzuzjmd** [uzuzjmd/COMPBASE#96]
1) implement /courses/sync
2) implement /activities/sync
3) implement /users/sync
4) implement loading cache
5) change login to POST with flags for the sync operations
6) implement time based limit on the syncs (?)

It would be good to decide if this is still included in the mobile project. Starting a branch sync in any case.

**Comment by mantir** [comment]
1, 2, 3) The most important syncs would be users and courses. (Activity sync has low priority. )
4) What is meant by loading cache? 
5) It would be great to have this login operation where user specific data is persisted in the db: At least the user and his/her courses. (Activity sync has low priority. )
6) Time based limit isn't necessary I think because the sync operations are triggered by parameters.

**Comment by uzuzjmd** [comment]
Works with simple tests. Can be used as an alternative to the user/exists login
